version : '3.9'

services:
  blue:
    container_name: blue
    image: daruda241221/daruda
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - daruda-blue-volume:/logs/daruda-blue-volume


  green:
    container_name: green
    image: daruda241221/daruda
    expose:
      - 8080
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - daruda-green-volume:/logs/daruda-green-volume
