version : '3.9'

services:
  blue:
    container_name: blue
    image: daruda241221/daruda
    expose:
      - 8080
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://daruda-db.czk6okg68de0.ap-northeast-2.rds.amazonaws.com:3306/daruda
      - SPRING_DATASOURCE_USERNAME=daruda
      - SPRING_DATASOURCE_PASSWORD=daruda8688!
    volumes:
      - daruda-blue-volume:/logs/daruda-blue-volume




  green:
    container_name: green
    image: daruda241221/daruda
    expose:
      - 8080
    ports:
      - "8082:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://daruda-db.czk6okg68de0.ap-northeast-2.rds.amazonaws.com:3306/daruda
      - SPRING_DATASOURCE_USERNAME=daruda
      - SPRING_DATASOURCE_PASSWORD=daruda8688!
    volumes:
      - daruda-green-volume:/logs/daruda-green-volume
