server:
  port : 8080

spring :
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    credentials:
      access-key: ${S3ACCESSKEY}
      secret-key: ${S3SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  file:
    path : logs
  level:
    org.springframework.web: DEBUG
    org.hibernate.type: TRACE
jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
  refresh-token-expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
