name: CI/CD
env:
  SECRET_CODE : ${{ secrets.SECRET_CODE}}

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      # JDK 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application.yml
        run: |
          mkdir -p ./src/main/resources
          cd ./src/main/resources
          touch ./applicationyml
          echo "${{ secrets.APPLICATION_DEV }}" > ./application.yml
        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKER_LOGIN_ACCESSTOKEN }}

      - name: Docker build & push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: daruda241221/daruda

  CD:
    needs: CI
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            LOG_DIR="/home/ubuntu/daruda_log"
            if [ ! -d "$LOG_DIR" ]; then
              mkdir -p "$LOG_DIR"
              echo "로그 폴더 생성 완료: $LOG_DIR"
            fi

            # 기존 배포 스크립트 실행
            cd ~
            ./deploy.sh
